# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='post_code',
            field=models.TextField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
