# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_profile_post_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='post_code',
            field=models.CharField(max_length=10),
        ),
    ]
