# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('fee', models.IntegerField()),
                ('location', models.CharField(choices=[('ACT - Canberra', 'ACT - Canberra'), ('NSW - Parramatta', 'NSW - Parramatta'), ('NSW - Sydney', 'NSW - Sydney'), ('GLD - Brisbane', 'GLD - Brisbane'), ('SA - Adelaide', 'SA - Adelaide'), ('VIC - Melbourne', 'VIC - Melbourne'), ('WA - Perth', 'WA - Perth'), ('DH - Dhaka', 'DH - Dhaka')], max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('details', models.TextField(max_length=255)),
            ],
        ),
    ]
