# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 16:34
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='details',
            field=tinymce.models.HTMLField(),
        ),
    ]
