# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='location',
            field=models.CharField(choices=[('ACT - Canberra', 'ACT - Canberra'), ('NSW - Parramatta', 'NSW - Parramatta'), ('NSW - Sydney', 'NSW - Sydney'), ('GLD - Brisbane', 'GLD - Brisbane'), ('SA - Adelaide', 'SA - Adelaide'), ('VIC - Melbourne', 'VIC - Melbourne'), ('WA - Perth', 'WA - Perth'), ('DH - Dhaka', 'DH - Dhaka')], default=None, max_length=100),
        ),
    ]
