# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='training',
            old_name='user_id',
            new_name='user',
        ),
    ]
