# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_auto_20170222_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='participant',
            field=models.CharField(choices=[('individual', 'individual'), ('group', 'group'), ('business', 'business')], default='individual', max_length=50),
        ),
    ]
